const LOGIN_USER = 'LOGIN_USER'
const LOGOUT_USER = 'LOGOUT_USER'
export const LOGIN_USER_INIT = `${LOGIN_USER}_INIT`
export const LOGIN_USER_SUCCESS = `${LOGIN_USER}_SUCCESS`
export const LOGIN_USER_ERROR = `${LOGIN_USER}_ERROR`
export const LOGOUT_USER_INIT = `${LOGOUT_USER}_INIT`
export const LOGOUT_USER_SUCCESS = `${LOGOUT_USER}_SUCCESS`
export const LOGOUT_USER_ERROR = `${LOGOUT_USER}_ERROR`
