const LIST_PRODUCTS = 'LIST_PRODUCTS'
export const LIST_PRODUCTS_INIT = `${LIST_PRODUCTS}_INIT`
export const LIST_PRODUCTS_SUCCESS = `${LIST_PRODUCTS}_SUCCESS`
export const LIST_PRODUCTS_ERROR = `${LIST_PRODUCTS}_ERROR`